version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rspec_sample_development
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    container_name: mysql

  rails_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - mysql
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    container_name: web

volumes:
  db-store:
